version: '3'
services:
  sync:
    profiles:
      - dummy

  spec-generator:
    image: local/bus-documentation-test
    build:
      context: ../..
      dockerfile: contribs/Dockerfile
    volumes:
      - ../../contribs/documentation.py:/app/documentation.py:ro
      - ../../wazo_bus:/app/wazo_bus:ro

  spec-validator:
    image: asyncapi/cli:1.7.3  # FIXME: revert to latest when 1.9.0 will be released

  rabbitmq:
    profiles:
      - dummy

  bus:
    profiles:
      - dummy
