FROM python:3.11-slim-bookworm
LABEL maintainer="Wazo Maintainers <dev@wazo.community>"

RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

RUN apt-get -q update && apt-get -yq install netcat-openbsd

WORKDIR /usr/src/wazo-bus
RUN pip install flask

COPY integration_tests/docker/entrypoint.sh /usr/bin/entrypoint.sh
COPY integration_tests/docker/remote-bus-pilot.py /usr/src/remote-bus-pilot.py
COPY . /usr/src/wazo-bus

WORKDIR /usr/src
RUN pip install -e wazo-bus

ENTRYPOINT ["/usr/bin/entrypoint.sh"]
